title: "わかりやすさ・わかりにくさという観念に関する認識論的考察"
summary: '"わかりやすい" "わかりにくい"という、多くの人々で共通して抱かれながらしばしばその不一致が見受けられる観念について、その性質とその観念を通じて我々が語りうる限界および可能性を考察する'
topics: ["ポエム"]
published: false
price: 0
chapters:
  - introduction
  - abstract
  - reduction
  - whole-of-idea
  - limitation-and-possibility-of-idea
  - from-subjectivity-to-conviction
  - conclusion
  - prospect
  - references
